services:

    # RabbitMQ
    rabbitmq:
        image: rabbitmq:3.13-rc-management
        ports:
        - "5672:5672"
        - "15672:15672"
        volumes:
          - rabbitmq-data:/var/lib/rabbitmq
          - rabbitmq-log:/var/log/rabbitmq
        environment:
          - RABBITMQ_DEFAULT_USER=admin
          - RABBITMQ_DEFAULT_PASS=1234
          - RABBITMQ_DEFAULT_VHOST=/

volumes:
  rabbitmq-data:
  rabbitmq-log:
